version: "3.8"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "4001:4001"  # Host 4001 maps to container 4001
    environment:
      NODE_ENV: "production"
      AWS_REGION: "${AWS_REGION}"
      AWS_ACCESS_KEY: "${AWS_ACCESS_KEY}"
      AWS_SECRET_KEY: "${AWS_SECRET_KEY}"
      S3_BUCKET: "${S3_BUCKET}"
      PORT: 4001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
    ports:
      - "4000:80"  # Host 4000 maps to container 80 (NGINX default)
    environment:
      REACT_APP_BACKEND_URL: "http://localhost:4001"
    depends_on:
      backend:
        condition: service_healthy
