name: Lint

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install Frontend Dependencies
        run: npm ci --prefix frontend

      - name: Install Backend Dependencies
        run: npm ci --prefix backend

      - name: Lint Frontend
        run: npm run lint --prefix frontend

      - name: Lint Backend
        run: npm run lint --prefix backend
